version: '3.8'

services:
  db:
    container_name: simple-restaurant-db
    image: postgres:16.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "restaurant"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
  api:
    container_name: simple-restaurant-api
    command: run
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - docker-compose.env
    ports:
      - "8080:8080"
    volumes:
      - ./target:/code/target
      - ./src:/code/src
      - ./Cargo.toml:/code/Cargo.toml
    depends_on:
      - db
